### ISSUE TITLE
Create regEllipse.c Module

### ISSUE THREAD

**Issue by eholum** [eholum/RegionLibraryTasks#34]

**Comment by janlyn7** [comment]
In my testing of regEllipse.c functions, noticed that results from regEllipse->calcExtent() 
    Extent: (0.464466, -0.535534), (7.535534, 6.535534)

are different from the regression test using regExtent():
    Extent: (0.464466, 0.000000), (7.535534, 6.535534)

Turns out regExtent() calls regExtentShape() and regTrimExtent(), which truncates shape coords to fit within the region, leading to slightly different output.
